"""Create relationship between shipping and orders

Revision ID: c07da2a9ee60
Revises: 9a87f9f509f1
Create Date: 2024-04-01 13:46:00.671057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07da2a9ee60'
down_revision = '9a87f9f509f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'shipping', ['shipping_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shipping_id')

    # ### end Alembic commands ###
